timezone: Europe/Amsterdam
title: AirPath's homepage
tagline: still in development :)
description: Just a description
url: "https://airpathoncode.github.io"
github:
	username: AirPathOnCode
social:
	name: AirPath144
	email: AirPath
	discord: AirPath144