timezone: Europe/Amsterdam
title: AirPath's homepage
tagline: my blog
description: A blog
url: "https://airpathoncode.github.io"
github:
	username: AirPathOnCode
social:
	name: AirPath144
	email: AirPath
	discord: AirPath144